title: Agile Open Ecuador
logo: /assets/img/logo.png
agile_ecuador_logo: /assets/img/agile-ecuador-logo.png
email: comunidad@agileecuador.org
description: >- # this means to ignore newlines until "baseurl:"
  Este año realizaremos la novena edición en Quito. Co-crearemos libremente bajo un formato de
  charlas abierto donde cada quién es un actor clave en el éxito de este espacio 
  para colaborar y mejorar.
twitter_username: agileEcuador
github_username:  agileEcuador


# Build settings
markdown: kramdown
theme: jekyll-theme-tactile
plugins:
  - jekyll-feed

