version: '3'
services:
  website:
    image: agileecuador/aoec-webdev:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec jekyll serve --watch --force_polling --host 0.0.0.0
    ports:
      - "4000:4000"
    volumes:
      - .:/src
    environment:
      - JEKYLL_BUILD_REV=${JEKYLL_BUILD_REVISION:-11161984}
